pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
      
        stage('instalar npm') {
                    steps {
                        sh "npm install"
                    }

                }
         stage('ejecturar test') {
                    steps {
                     sh "npm run test"
                    }

                }
           stage('Construir build') {
                    steps {
                     sh "npm run build"
                    }

                }
          
        }
    }
}
