pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
                reuseNode true 
            }
            stages {
                stage('Instalar') {
                    steps {
                       sh 'npm install'
                    }
                }
                stage('run test') {
                    steps {
                       sh 'npm run test'
                    }
                 }
                stage('run build') {
                    steps {
                       sh 'npm run build'
                    }

                }
            }
        }
    }

}