pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' 
                reuseNode true 
                }
           
            }
            stages {
                stage('Instalar') {
                    steps {
                       sh 'npm install'
                    }
                }
                stage('run test') {
                    steps {
                       sh 'npm run test'
                    }
                 }
                stage('run build') {
                    steps {
                       sh 'npm run build'
                    }

                }
      
            }
        }
        stage('delivery to docker: crear imagen docker') {  
            
                steps {
                    script { 
                    docker.withRegistry('http://localhost:8082','nexus-key') {
                    sh 'docker build -t localhost:8082/mi-proyecto-devops .'
                    sh "docker tag localhost:8082/mi-proyecto-devops localhost:8082/mi-proyecto-devops:${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
                    sh 'docker push localhost:8082/mi-proyecto-devops'
                    sh "docker push localhost:8082/mi-proyecto-devops:${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
                         }

                     }  
                }

         }     
         stage('Deploy por Compose') {  
            
                steps {
                    script { 
                    docker.withRegistry('http://localhost:8082','nexus-key') {
                    sh 'docker-compose -f ./cicd/docker-compose.yaml pull'
                    sh 'docker-compose -f ./cicd/docker-compose.yaml -p mi-proyecto-devops up --force-recreate --build'
                            }

                        }
                }

         }  

    }
}